### ISSUE TITLE
multicopter and groundvehicle not using movePerSec_m

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#160]
**The problem**
The platforms of type `multicopter` and `groundvehicle` do not use the speed (`movePerSec_m) specified in the `platformSettings` of the survey XML. For the multicopter it seems to be always around 10 m/s, for the groundvehicle 4 m/s (?). 

**How to reproduce**

I am attaching two survey XMLs for reproducing the issue (modifications of surveys which we have in the repo):
- survey XMLs: [platform_speed.zip](https://github.com/3dgeo-heidelberg/helios/files/7943285/platform_speed.zip)

**Expected behavior**

The platforms use the speed specified in the survey XMLs with `speedPerSec_m`. If different parameters for the speed are set for different legs, we expect the simulated point clouds of the legs to look different. 

**Actual behavior**

The simulated point clouds always look the same, no matter what `movePerSec_m` is specified. If I checked correctly, it is 10 m/s for the `mutlicopter` platform and 4 m/s for the `groundvehicle`.

**Your environment (please complete the following information):**
 - OS: Windows 10
 - HELIOS++ version (or Git revision) that exhibits the issue: 1.1.0; current git revision on dev (20627d55bfc12508f45a056e32dd620f73ddd446) - but issue already present in earlier versions

**Can you identify the location in the source code where the problem exists? (Optional)**

Probably https://github.com/3dgeo-heidelberg/helios/blob/dev/src/platform/HelicopterPlatform.cpp and https://github.com/3dgeo-heidelberg/helios/blob/dev/src/platform/GroundVehiclePlatform.cpp ?

**Comment by miguelyermo-heidelberg** [comment]
I just did a pull request adressing this issue (#165) . I would like everyone to perform several tests to ensure the fix is working as expected and the trajectories look fine. I'll let here a brief explanation of the issue and the solution in case anyone have some suggestions to improve it.

The problem was that the moving platforms having an engine (multicopter and groundvehicle) didn't take into account the provided values of `movePerSec_m`. I focused on solving the issue without alter the physical behaviour of these platforms, so I did the following: the maximum speed of the platform is now limited by the minimum value between the maximum speed achievable by the engine itself and the value provided by the user. I added a warning at the end of each leg to inform the user what happened with the speed (4 possible outcomes): 
1) The speed was limited by the engine and the user speed was not reached: Solution: Increase `engine_max_force` (Only available in the multicopter platform afaik)
2) The speed was limited by the engine at the exact value provided by the user: Ideal case (unlikely). Nothing to do 
3) The speed was not limited by the engine but the user-provided speed was achieved. Nice, the logger inform that the speed can be increased if desired.
4) The speed was not limited by the engine and the user-provided speed was not achieved. Here the logger informs of the leg being too short to achieve the required speed. Another possibility is to inform that the drag coefficient is too high to achieve the given velocity.

The info messages are located in `MovingPlatform.cpp:97-126`. If any of you has a suggestion to make them clearer, let me know.
