### ISSUE TITLE
scannerSettings template behavior - scan angle increasing for each leg using the template

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#23]
When defining the `scanAngle_deg` via a `scannerSettings` template in the beginning of the survey XML file, the scan angle is not inherited to each leg using the template. Instead the scan angle increases for each leg using the template, at least with the new `risley` scanner optics.

The bug can be reproduced with [data/surveys/toyblocks/uls_toyblocks_livox.xml](https://github.com/3dgeo-heidelberg/helios/blob/main/data/surveys/toyblocks/uls_toyblocks_livox.xml). 

(Note: It seems like the issue occurs for all scanner optics, but for the existing scanners, the scan angle is always limited to the maximum possible value. For the new scanner optics ("risley"), part of the code is uncommented (see [src/scanner/beamDeflector/RisleyBeamDeflector.cpp](https://github.com/3dgeo-heidelberg/helios/blob/main/src/scanner/beamDeflector/RisleyBeamDeflector.cpp) line 64f.), so scan angle is not set to max scan angle.)

**Comment by albertoesmp** [comment]
When loading XML assets, radian values from template are temporary converted to degrees because to match format of user given ones. In consequence, the scan angle was incremented by a factor of 180/pi for each leg, since the old value was overwritten. It has been fixed and now all legs from given survey start at 23 degrees.

Please check everything works as expected and close the issue if so. Otherwise, let me know what is going on so I can dig deep into this bug.
