### ISSUE TITLE
Could NOT find Boost (missing: zlib) (found suitable version "1.75.0",   minimum required is "1.71.0")

### ISSUE THREAD

**Issue by saadatshakeel** [3dgeo-heidelberg/helios#24]
Hello,

When I am trying to build Helios project through CMake, the build fails and I encounter following error: Could NOT find Boost (missing: zlib) (found suitable version "1.75.0", minimum required is "1.71.0"), Can you please guide me what is the issue? Because I have my zlib unzipped in the correct directory. Please convey the possible solutions

Thank you

**Comment by albertoesmp** [comment]
Hello and thanks for opening this issue.

I'm answering assuming you are using a Linux OS, otherwise please let us know which OS are you working with.

A fast possible solution would be to use the system package manager to install zlib. For instance, in Ubuntu it could be done with:
`sudo apt-get install zlib1g zlib1g-dbg  zlib1g-dev`
 If you are using a non-debian based Linux distribution then a different package manager must be used but probably zlib is already available (yum for centOS and Scientific-Linux, equo for Gentoo, pacman and aur for Archlinux, etc.)

If you install zlib at system level as proposed before, then CMake should be capable of finding it and build successfully. I think this applies for both, Linux and Windows.

On the other hand, if you need to compile zlib manually, then its path must be explicitly specified. There are different ways to do this. On Linux, a simple one would be to export an environment variable so cmake knows where to find zlib. This can be achieved using `export CMAKE_LIBRARY_PATH="<ZLIB PATH>" && cmake ...` where `<ZLIB PATH>` must be replaced by the path where zlib is located and cmake ... would be the cmake invokation you are currently trying. On Windows, maybe you are using CMakeGUI so you could add the variable here.

Here you have a Link to CMake documentation for find_library and find_package so you can see what each variable does:
https://cmake.org/cmake/help/latest/command/find_library.html
https://cmake.org/cmake/help/latest/command/find_package.html

At the moment, Helios++ is using find_package to handle zlib at CMake scripts. If I'm not wrong this implies calling a script which also calls find_library.

Finally, if previous steps dont fix the problem, I would really appreciate to have more information. It would be really useful if you could run the following command `tree "<HELIOS DIRECTORY>"` so I can see the file tree and analyze where each file is located. For instance, in my case the command would be `tree "/home/uadmin/git/helios-plusplus"` It would be also really useful to know the concrete linux distribution you are working with.


Kind regards,
Alberto
