### ISSUE TITLE
How to correctly add attributes to a LAS output

### ISSUE THREAD

**Issue by waitforraining** [3dgeo-heidelberg/helios#425]
I have already used stripID to write the data returned by multiple legs into one LAS file to avoid processing multiple times. At the same time, I also need to add an index similar to scanIdx in the LAS file. I modified the compiled code, but the result of running it is not correct.
How should I correctly modify this part of the code to add attributes to the LAS output?
in LasWriterSpec i add scannerAttrIdx and scannerAttrStart 
![image](https://github.com/3dgeo-heidelberg/helios/assets/53138029/842e10b8-d5f4-41a0-a0f3-70a108a4cd1a)

![image](https://github.com/3dgeo-heidelberg/helios/assets/53138029/11987958-988f-40c8-b18b-d9dd9521aa84)
![image](https://github.com/3dgeo-heidelberg/helios/assets/53138029/90fb53ff-46d7-47cd-b112-0f1c09995663)
![image](https://github.com/3dgeo-heidelberg/helios/assets/53138029/9c8daf6e-2e29-4979-9f2c-185c7049a72b)
in LasMeasurementWriteStrategy
![image](https://github.com/3dgeo-heidelberg/helios/assets/53138029/e742bb92-d971-4c97-89e1-2abbe62360c8)
![image](https://github.com/3dgeo-heidelberg/helios/assets/53138029/fa95a246-3dcc-4691-b12a-e64c5836726f)
After this,i use laspy to read las.Even though I already have the 'scanidx' attribute, the attribute values are incorrect.

**Comment by albertoesmp** [comment]
Hi!

How are you configuring the `scannerType`? If you look in the addExtraAttributes, you can use 9 for double or 5 for int, as done with the other extra attributes. I'd also recommend having a look at the LASTools examples (https://github.com/LAStools/LAStools/tree/master/LASlib/example) to find something close to what you want. Then, you can compare it with your implementation to check that you are not missing any steps.

In case you don't manage to extend the LAS output as you want, you might also extend the `filems::write::strategies::DirectMeasurementWriteStrategy` to export your output in text format. Then you can check that it is correct. If it is not, maybe the problem is the data itself and not the writing. Also, you can always convert the ASCII point clouds to LAS/LAZ using LASTools.


Thank you for using the HELIOS++ simulator, and let us know if you have further issues.

**Comment by waitforraining** [comment]
Hi!
I am a rookie in C++ and made a mistake. I should use legIdx to tag point,but i use scanIdx in pointMeasurement. Learn from you response,I revise code,and get correct legIdx like this.
![image](https://github.com/3dgeo-heidelberg/helios/assets/53138029/ecbb69d6-9b27-4a76-aa0e-163d15977516)
it is funny.
thanks you!
