### ISSUE TITLE
Platform noise question

### ISSUE THREAD

**Issue by AntoineLafon** [3dgeo-heidelberg/helios#463]
Hello,

I've noticed that in your paper (Section 3.8) you discuss platform noise that can simulate trajectory estimation error. However, according to my tests, it does not appear that there is an estimation error. Instead, it seems more like there is noise in the trajectory, and the platform knows its position perfectly.

Could you please let me know if my guess is correct?

**Comment by han16nah** [comment]
Dear @AntoineLafon 

to reply with the words of @lwiniwar:
yes, your guess is correct. The platform noise creates a point cloud with correct coordinates, i.e., objects are depicted at their real locations, while the position from where they are observed is noisy. 
We did put some thought into this, and originally also had a different implementation. However, to be most flexible in terms of scenarios, we opted this implementation, because:

a) a trajectory error/noisy direct georeferencing can be estimated by shifting the resulting point cloud following some function of time (e.g., dX, dY, dZ = f(t) with f continuous). This can easily be applied by a (Python) script after running Helios++, while
b) observations from locations that are not directly on the planned trajectory lead to different occlusions, incidence angles, and other effects, that influence the number of recorded points, the reflection simulation, etc., which cannot be easily changed by just operating on the point cloud.
