### ISSUE TITLE
create and visualize the scene 

### ISSUE THREAD

**Issue by xjy11** [3dgeo-heidelberg/helios#52]
Hello！
I am intereted in simulating the ALS full-waveform data with the TLS discrete points. 
According to the Wiki, I should create a 3D scene made up of detailedVoxels for crown and OBJ-model for stem first, so I used the voxelizer_write_vox.py to voxelize the point clouds. But how to watch the .vox file I voxelized to make sure what I did is correct? Besides, which kind of tool should I use to watch the stem object and the crown voxels at the same time? 
Thank you a lot!

**Comment by han16nah** [comment]
Hi,
for simple voxelisation, you can also use the xyz point cloud loader, which voxelizes the point cloud within HELIOS++ using your defined voxel size. If your scene is not very large, this might be the easier way.
The detailedVoxels make especially sense, if you have some transmittance/plant area density info, e.g. computed using AMAPVox software.

If you want to work with voxeliser_write_vox.py, I have attached a script [voxelizer_write_mesh.zip](https://github.com/3dgeo-heidelberg/helios/files/6726015/voxelizer_write_mesh.zip) which performs the same voxelisation, but saves the output to an .obj-file, which can be visualised in e.g. CloudCompare (together with a mesh of the stem). 

For visualising the simulation, including your scene objects, you can start your simulation with [helios.py](https://github.com/3dgeo-heidelberg/helios/blob/main/pyhelios_demo/helios.py).
Instead of `run\helios <path-to-survey.xml>` you execute: `python helios.py <path-to-survey.xml>` from the command line (assuming you copied the file to the root directory). You can use all the usual parameters (e.g. `--lasOutput`) when calling the script.

Feel free to ask if anything was not clear!

Best,

Hannah
