### ISSUE TITLE
Get RGB from scanning

### ISSUE THREAD

**Issue by fkaufm** [3dgeo-heidelberg/helios#99]
In our research, we would like to use Helios++ (with Blender) to acquire synthetic data for semantic segmentation of pointclouds from buildings. For that matter it would be helpful if one could get RGB values in addition to XYZ and intensity. Is there such a feature in Helios++? Or do you plan to integrate it?

**Comment by lwiniwar** [comment]
Hello @fkaufm!
Thank you for your interest in our software. The measurement process as simulated in HELIOS++ is built to closely resemble the inner workings of laser scanners. As such, they are by design mono- or bichromatic, and only return one intensity value per point. Any RGB information is added in a separate step, i.e., by taking panoramic pictures (for TLS) or videos (for MLS), and subsequently mapping the points into the image space, where the color is assigned.
This is possible if you have information about the intrinsic (camera definition) and extrinsic (position relative to the scan origin) properties of the photos. However, this is clearly a post-processing step and outside of the scope of laser scanning per se. We therefore have no plans to include such a feature in HELIOS++. 

If you are modelling with Blender anyway, you can use it to create virtual photographs (from the viewpoint of the scan positions) which you can subsequently map your point cloud onto. I have found some tools that allow you to do this, but I'm sure there's more: https://autoware.readthedocs.io/en/feature-documentation_rtd/DevelopersGuide/PackagesAPI/detection/pixel_cloud_fusion.html
Our wiki further explains how you can use material definitions to assign classes to the point cloud, which you can use, e.g., as labels in your semantic segmentation: https://github.com/3dgeo-heidelberg/helios/wiki/Scene#material-files
